### PR TITLE
Added PHP 7.3 support - updated Travis CI configuration

### PR DESCRIPTION
**Pull request by webimpress**

### CODE REVIEW

**Comment by webimpress** [comment]
@weierophinney should I rebase this branch and we have it merged it to v4 or we will have another v3 release with it?

**Comment by weierophinney** [comment]
@webimpress We'll have another v3 release, so please go ahead and rebase.

**Comment by webimpress** [comment]
@weierophinney 

> We'll have another v3 release, so please go ahead and rebase.

The problem is that develop is already on v4 so if I rebase it's not gonna go to v3, I guess. I think we should have another branch and then I can rebase and change target of that PR.

**Comment by weierophinney** [comment]
@webimpress We can issue a new minor release from the master branch instead; that's what we just did with zend-db as well.

**Comment by webimpress** [comment]
@weierophinney rebased and changed target to `master`.

**Pull request merged**
